#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Miyuu Taniguchi
# SPDX-License-Identifier: BSD-3-Clause

import sys


#各選手のスコアを計算
def calculate_score(player):
    return(
        + player["hits"] * 2             #安打: +2点
        + player["runs_batted_in"] * 3   #打点: +3点
        + player["home_runs"] * 4        #本塁打: +4点
        + player["steals"] * 2           #盗塁: +2点
        - player["errors"] * 5           #エラー: -5点
    )

print("各選手の成績を以下のように入力してください(入力し終えたら改行してCtrl+D)")
print("名前,打数,安打,打点,本塁打,盗塁,失策")

players = []


while True:
    players.clear()
    valid_input = True
    
    for line in sys.stdin:
        data = line.split(",")   #入力データを","で区切る
        if len(data) != 7:       #dataに含まれる要素が７つのときのみ反映
            print("入力されたデータ数が正しくありません")
            valid_input = False
            break
        try:                     #名前は文字列、成績は整数に変換
            player = {
                "name": data[0],
                "at_bats": int(data[1]),
                "hits": int(data[2]),
                "runs_batted_in": int(data[3]),
                "home_runs": int(data[4]),
                "steals": int(data[5]),
                "errors": int(data[6])
            }
        except ValueError:      #数字以外の文字が入力されたときのエラー
            print("数値入力が正しくありません")
            valid_input = False
            break

        player["score"] = calculate_score(player)
        players.append(player)

    if valid_input and players:
        break
    else:
        print("\nデータを再入力してください")

players = sorted(players, key=lambda x: x["score"], reverse=True)   #スコアの降順に選手を並び替え

print("\n試合のMVP判定結果")
rank = 1
for player in players:
    print(f"{rank}位: {player['name']} (スコア:{player['score']})")
    rank += 1

if players:
    print(f"\n今日のMVPは{players[0]['name']}です")
else:
    print("\n選手の情報が入力されていません")
